name: TownyFractions
version: '${project.version}'
main: ru.cwcode.fractions.Fractions
api-version: 1.16
depend: [ Towny, QualityArmory, Banks, Vehicles, TownyTerritory, Vault, Commands, Config ]
commands:
  fraction:
  prison:
  setshoker:
  blockCMD:

