name: TownyFractions
version: '${project.version}'
main: tkachgeek.fractions.Fractions
api-version: 1.16
depend: [ Towny, QualityArmory, Banks, Vehicles, TownyTerritory, Vault, Commands, Config ]
commands:
  fraction:
  blockCMD:

